api/urls.py
from django.urls import path
from . import views

app_name = 'api'

#URL patterns for the API endpoints
urlpatterns = [
    #Endpoint for product name autocomplete
    path('product-name-autocomplete/', views.product_name_autocomplete, name='product-name-autocomplete'),
    #Endpoint for submitting customer feedback
    path('submit-feedback/', views.submit_feedback, name='submit-feedback'),
]

customer_sentiment_analysis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from website import views


urlpatterns = [
    
    path("", views.index, name="index"), 
    path('admin/', admin.site.urls),
    path('customers/', include('customers.urls')),
    path('customers/', include("django.contrib.auth.urls")),
    path('api/', include('api.urls')),
    

]

customers/urls.py
from django.urls import path, include
from .views import SignUpView
from . import views
from django.contrib.auth import views as auth_views



app_name = 'customers'
urlpatterns = [
        path("signup/", SignUpView.as_view(), name="signup"),
        path('login/', auth_views.LoginView.as_view(), name='login'),

        path("logout/", auth_views.LogoutView.as_view(), name="logout"),


]

website/urls.py
from django.urls import path
from . import views
from django.views.generic.base import TemplateView


app_name = 'website'
urlpatterns = [
   path("", views.index, name="index"),
]

api/models.py
from django.db import models

# Create your models here.

customers/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

#Custom Customer model extending the built-in AbstractUser
class Customer(AbstractUser):
    pass
   
    def __str__(self):
        return self.username

website/models.py
from django.db import models
from customers.models import Customer

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    rating = models.FloatField(default=0.0)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    # Foreign key to the Customer model
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
     # Foreign key to the Product model
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    feedback_text = models.TextField()
    sentiment = models.CharField(max_length=20)  

    def __str__(self):
        return f"{self.customer.username} - {self.product.name}"

customers/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import Customer


class CustomerCreationForm(UserCreationForm):

    class Meta:
        model = Customer
        fields = ("username", "email")

class CustomerChangeForm(UserChangeForm):

    class Meta:
        model = Customer
        fields = ("username", "email")

api/views.py
from django.shortcuts import render
from rest_framework import generics, status
from website.models import Product, Feedback
from .serializers import ProductSerializer, FeedbackSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.db.models import Q
from ml_model.sentiment_analysis_model import sentiment_analysis

#api view for product name autocomplete
@api_view(['GET'])
def product_name_autocomplete(request):
    # Get the query from the request
    query = request.GET.get('q', '')
    #check if the data entered by the user matches any of the data in database
    products = Product.objects.filter(Q(name__icontains=query))  # case insensitive
    #Serialize the products
    serializer = ProductSerializer(products, many=True)
    #return data to frontend
    return Response(serializer.data)


 #API view for submitting feedback 
@api_view(['POST'])
def submit_feedback(request):
    print(f"Request data: {request.data}")
    #initialize serializer with incoming data
    serializer = FeedbackSerializer(data=request.data, context={'request': request})
    
    # perform sentiment analysis only if data in serializer is valid
    if serializer.is_valid():
        #serializer contains customer and product details and feedback sent from frontend
        #extract feedback for sentiment analysis
        feedback_text = serializer.validated_data['feedback_text']

        #perform sentiment analysis on feedback text
        sentiment = sentiment_analysis(feedback_text)  
        # save the sentiment analysis result into database
        feedback = serializer.save(sentiment=sentiment)
        
        #Return the sentiment analysis result to the customer 
        return Response({
            'sentiment': sentiment, 
           
        }, status=status.HTTP_201_CREATED)
    # If the serializer is not valid, return the errors with a 400 status code
    else:
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

customers/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomerCreationForm

#New user registration
class SignUpView(CreateView):
    #form to be used for the customer registration process
    form_class = CustomerCreationForm
    # redirects the user to the login page after successful registration
    success_url = reverse_lazy("login")
    #template to render the sign-up form
    template_name = "registration/signup.html"

website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, 'website/index.html')

website/templates/website/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Product Website{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  
</head>
<body>
  <main>
    <h1>Welcome</h1>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    
  </main>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

website/templates/website/index.html
{% extends "website/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="d-flex justify-content-between ">
    <h4> Hi, {{ user.username }}! </h4>
    <form method="post" action="{% url 'logout' %}">
      {% csrf_token %}
      <button type="submit">Logout</button>
    </form>
</div>
    <!--Feedback Form-->
  <form id="feedbackForm" method="POST">
    {% csrf_token %}
    <!--Name of the Logged in Customer-->
    <div>
      <label for="userName" class="form-label">Name:</label>
      <input type="text" class="form-control" id="userName" name="user_name" value="{{ user.username }}" readonly>
    </div>
    
    <input type="hidden" id="userId" name="user_id" value="{{ user.id }}">

    <div>
      <label class="form-label" for="productName">Product:</label>
      <input class="form-control" type="text" required id="productName" name="product_name" placeholder="Enter product name" autocomplete="off">
      <div id="autocompleteDropdown" style="display: none; background: rgb(197, 196, 196); border: 1px solid #ccc;"></div>
    </div>
    <div> 
      <!--Feedback entered by customer-->  
      <label class="form-label" for="feedbackText">Feedback:</label>
      <textarea class="form-control" id="feedbackText" rows="10"  required name="feedback_text" placeholder="Enter your feedback"></textarea>
    </div>
    <div class="d-flex justify-content-center"><button type="submit">Submit</button></div>
    
  </form>
  <!--Sentiment Display-->
  <div class="d-flex justify-content-center"><h6 class="display-6" id="sentimentResult"></h6></div>

  
<script>
  //Product Name Autocomplete
    let selectedProductId = null;
    document.getElementById('productName').addEventListener('input', function () {
        const query = this.value;
        const dropdown = document.getElementById('autocompleteDropdown');

        //hide dropdown if query is empty
        if (!query) {
            dropdown.style.display = 'none'; 
            return;
        }
        
        //fetch data for autocomplete
        fetch(`/api/product-name-autocomplete/?q=${query}`)
            .then(response => response.json())
            .then(data => {
              //clear previous data
                dropdown.innerHTML = '';

                if (data.length > 0) {
                  //show dropdown if data is found
                    dropdown.style.display = 'block'; 
                    data.forEach(product => {
                        
                        const item = document.createElement('div');
                        item.textContent = product.name;
                        item.dataset.productId = product.id;

                        //fill the product field with value selected from dropdown
                        item.addEventListener('click', function () {
                            document.getElementById('productName').value = product.name; 
                            selectedProductId = product.id; 
                            dropdown.style.display = 'none'; //hide dropdown after filling product name field
                        });

                        dropdown.appendChild(item); // add products into the suggestion dropdown list
                    });
                } else {
                    dropdown.style.display = 'none'; //hide dropdown when no data
                }
            })
            .catch(error => {
                console.error('Error fetching autocomplete suggestions:', error);
                dropdown.style.display = 'none';
            });
    });

//hide dropdown if user clicks outside
    document.addEventListener('click', function (event) {
        const dropdown = document.getElementById('autocompleteDropdown');
        if (!dropdown.contains(event.target) && event.target.id !== 'productName') {
            dropdown.style.display = 'none';
        }
    });


      //Form submission for sentiment analysis
      document.getElementById('feedbackForm').addEventListener('submit', function(event) {
        event.preventDefault();
      
        const feedback_text = document.getElementById('feedbackText').value;
        const user_id = document.getElementById('userId').value;
        //product field can not be empty
        if (!selectedProductId) {
            alert('Please select a product');
            return;
          }
        //sending customer , product and feedback data to backend
        fetch('/api/submit-feedback/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCsrfToken(),  
            },
            body: JSON.stringify({
                customer: user_id,
                product: selectedProductId,  
                feedback_text: feedback_text
            })
        })
        .then(response => response.json())
        .then(data => {
            console.log(data.sentiment);
            document.getElementById('sentimentResult').textContent = `Sentiment: ${data.sentiment}`;
        });
      });



    //csrf token
      function getCsrfToken() {
        
        const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        return csrfToken;
      }
</script>

{% else %}
<!--Log in and Sign Up buttons if Customer is not authenticated-->
  <p>You are not logged in</p>
  <a type="button" class="btn btn-primary" href="{% url 'customers:login' %}">Log In</a> |
  <a type="button" class="btn btn-primary" href="{% url 'customers:signup' %}">Sign Up</a>
{% endif %}
{% endblock %}